[build]
  command = "python build.py"
  publish = "dist"

[dev]
  command = "python -m http.server"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

